# first you need to make directories for where you'll store the files
# in this code, find and replace all "/path/to/your/preferred/location/" with your preferred download location, including at "/" at the end. 
# the rest will be organized by climate scenario (or historical), followed by model, followed by data type (precipitation, max temp, min temp).
# the "-p" option in the "mkdir" command will make the whole path if it does not exist yet 

mkdir -p /path/to/your/preferred/location/rawdata/historical/ACCESS1-0/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/ACCESS1-0/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/ACCESS1-0/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/bcc-csm1-1/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/bcc-csm1-1/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/bcc-csm1-1/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/BNU-ESM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/BNU-ESM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/BNU-ESM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CanESM2/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CanESM2/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CanESM2/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CCSM4/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CCSM4/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CCSM4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CESM1-BGC/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CESM1-BGC/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CESM1-BGC/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CNRM-CM5/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CNRM-CM5/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CNRM-CM5/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CSIRO-Mk3-6-0/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CSIRO-Mk3-6-0/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/CSIRO-Mk3-6-0/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-CM3/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-CM3/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-CM3/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-ESM2G/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-ESM2G/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-ESM2G/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-ESM2M/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-ESM2M/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/GFDL-ESM2M/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/inmcm4/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/inmcm4/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/inmcm4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/IPSL-CM5A-LR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/IPSL-CM5A-LR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/IPSL-CM5A-LR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/IPSL-CM5A-MR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/IPSL-CM5A-MR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/IPSL-CM5A-MR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC-ESM-CHEM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC-ESM-CHEM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC-ESM-CHEM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC-ESM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC-ESM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC-ESM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC5/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC5/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MIROC5/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MPI-ESM-LR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MPI-ESM-LR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MPI-ESM-LR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MPI-ESM-MR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MPI-ESM-MR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MPI-ESM-MR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MRI-CGCM3/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MRI-CGCM3/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/MRI-CGCM3/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/historical/NorESM1-M/pr/
mkdir -p /path/to/your/preferred/location/rawdata/historical/NorESM1-M/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/historical/NorESM1-M/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/ACCESS1-0/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/ACCESS1-0/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/ACCESS1-0/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/bcc-csm1-1/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/bcc-csm1-1/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/bcc-csm1-1/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/BNU-ESM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/BNU-ESM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/BNU-ESM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CanESM2/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CanESM2/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CanESM2/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CCSM4/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CCSM4/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CCSM4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CESM1-BGC/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CESM1-BGC/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CESM1-BGC/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CNRM-CM5/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CNRM-CM5/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CNRM-CM5/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CSIRO-Mk3-6-0/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CSIRO-Mk3-6-0/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/CSIRO-Mk3-6-0/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-CM3/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-CM3/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-CM3/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-ESM2G/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-ESM2G/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-ESM2G/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-ESM2M/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-ESM2M/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/GFDL-ESM2M/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/inmcm4/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/inmcm4/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/inmcm4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/IPSL-CM5A-LR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/IPSL-CM5A-LR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/IPSL-CM5A-LR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/IPSL-CM5A-MR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/IPSL-CM5A-MR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/IPSL-CM5A-MR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC-ESM-CHEM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC-ESM-CHEM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC-ESM-CHEM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC-ESM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC-ESM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC-ESM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC5/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC5/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MIROC5/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MPI-ESM-LR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MPI-ESM-LR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MPI-ESM-LR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MPI-ESM-MR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MPI-ESM-MR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MPI-ESM-MR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MRI-CGCM3/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MRI-CGCM3/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/MRI-CGCM3/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/NorESM1-M/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/NorESM1-M/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp45/NorESM1-M/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/ACCESS1-0/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/ACCESS1-0/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/ACCESS1-0/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/bcc-csm1-1/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/bcc-csm1-1/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/bcc-csm1-1/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/BNU-ESM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/BNU-ESM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/BNU-ESM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CanESM2/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CanESM2/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CanESM2/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CCSM4/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CCSM4/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CCSM4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CESM1-BGC/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CESM1-BGC/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CESM1-BGC/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CNRM-CM5/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CNRM-CM5/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CNRM-CM5/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CSIRO-Mk3-6-0/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CSIRO-Mk3-6-0/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/CSIRO-Mk3-6-0/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-CM3/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-CM3/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-CM3/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-ESM2G/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-ESM2G/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-ESM2G/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-ESM2M/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-ESM2M/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/GFDL-ESM2M/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/inmcm4/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/inmcm4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/inmcm4/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/IPSL-CM5A-LR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/IPSL-CM5A-LR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/IPSL-CM5A-LR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/IPSL-CM5A-MR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/IPSL-CM5A-MR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/IPSL-CM5A-MR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC-ESM-CHEM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC-ESM-CHEM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC-ESM-CHEM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC-ESM/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC-ESM/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC-ESM/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC5/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC5/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MIROC5/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MPI-ESM-LR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MPI-ESM-LR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MPI-ESM-LR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MPI-ESM-MR/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MPI-ESM-MR/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MPI-ESM-MR/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MRI-CGCM3/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MRI-CGCM3/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/MRI-CGCM3/tasmin/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/NorESM1-M/pr/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/NorESM1-M/tasmax/
mkdir -p /path/to/your/preferred/location/rawdata/rcp85/NorESM1-M/tasmin/